### ISSUE TITLE
Contenttype unique constraint fail when loading fixtures

### ISSUE THREAD

**Issue by LauraMcCluskey** [AWGL/somatic_db#15]
Problem loading fixtures:

Could not load contenttypes.ContentType(pk=1000): UNIQUE constraint failed: django_content_type.app_label, django_content_type.model

Solution:

In fixtures file, "pk" needs to be changed to "id" for "contenttypes.contenttype"

**Comment by LauraMcCluskey** [comment]
fixed in issue15 branch

**Comment by erikwaskiewicz** [comment]
Fixed in pull request #17, but may reappear if fixtures are remade. I've linked to this issue is the readme so we have a record if we see this again.

@LauraMcCluskey7 can you add the command you used to fix this before we close the issue please?

**Comment by erikwaskiewicz** [comment]
I've just had to do this after updating the unittests, the issue came back after re-running the datadump command.

I don't think we can do this automatically as there are other fields that must stay as `pk`, we should use find and replace one by one and make sure we only replace instances within the `contenttypes.contenttype` model (which was right at the top for me, it was about 18 instances that needed replacing)
